[vlive]
title = "Red Velvet ─ Star Board"
url = "https://vlive.tv/channel/DCF447/board/4540"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
contentSelector = ".upload_time--wtBj9"
waitUntil = "networkidle"

[japan]
title = "Red Velvet Japan ─ News"
url = "https://redvelvet-jp.net/news/?page=1"
entrySelector = "div.news-entry.grid-x.grid-padding-x.small-up-1.medium-up-3 > a"
titleSelector = "h2[class='entry-title']"
linkSelector = "a.entry-body.cell"
imageSelector = "img"
contentSelector = "div[class='entry-date']"
